In [2]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [3]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check for ndimension
scaler.ndim

0

In [5]:
vector = tf.constant([20,30])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 30], dtype=int32)>

In [6]:
matrix = tf.constant([[10,10],[20,20]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[1.,2.,3.],[2.,4.,3.],[1.,2.,3.]],dtype="float16") # adding float numbers and changing datatype to float 16
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [2., 4., 3.],
       [1., 2., 3.]], dtype=float16)>

another_matrix.ndim

In [9]:
changeable_tensor = tf.Variable([7,10]) #note v is capital here 
unchangeable_tensor = tf.constant([7,10]) 
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [10]:
changeable_tensor[0] = 5
changeable_tensor

TypeError: ignored

In [11]:
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [12]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
random_1 = tf.random.Generator.from_seed(46)
random_1 = random_1.normal(shape=(3,2))
random_1

random_2 = tf.random.Generator.from_seed(46)
random_2 = random_2.normal(shape=(3,2))
random_2
random_1 == random_2

In [13]:
random_2 = tf.random.Generator.from_seed(46) 
random_2 = random_2.normal(shape=(3,2)) 
random_2 
random_1 == random_2

NameError: ignored

In [ ]:
not_shuffled = tf.constant([[10,7],[5,3],[3,5]])
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled,seed=42) #this does change all time

In [14]:
tf.random.set_seed(42) #this does not change for each run
tf.random.shuffle(not_shuffled) #operational level seed 
#if both operational level seed and global level seed are same then it will suffle in same order for all runs
#in above example operational seed is automatically set to 42

NameError: ignored

##create a tensor with all ones

In [ ]:
tf.ones([7,10])


## tensor with all zeros


In [15]:
tf.zeros([7,10])

<tf.Tensor: shape=(7, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## create a tensor from the numpy array


In [16]:
# it creates the np arrary from 1 to 24
import numpy as np
array_A = np.arange(1,25,dtype=np.int32)
array_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

X= tf.constant capital letter refers to matrix or scalar
y = tf.Variable small letter refers variable

In [17]:
A = tf.constant(array_A)
B = tf.constant(array_A,shape=(6,4))
A,B 

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>)

In [18]:
tf.size(A).numpy()
tf.size(B).numpy()

24

In [19]:
A.ndim

1

adding new dimensions with two methods
## expand_dims(array,axis)
##  [...,tf.newaxis]

In [20]:
rank2 = A[...,tf.newaxis]
rank2

<tf.Tensor: shape=(24, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]], dtype=int32)>

In [21]:
rank_2 = tf.expand_dims(A,axis=0) #array will be unchanged and with shape 1,24
rank_2 

<tf.Tensor: shape=(1, 24), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [22]:
C = tf.constant([[1,2],[3,4],[5,6]]) 
print(C)
rank_21 = tf.expand_dims(C,axis=-1)# this splits inner array into new array thus changes the shape (3,2,1)
rank_21

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

### Basic operation of tensor
basic operation are : 
`+`,`-`,`*`,`\`

In [23]:
tensor = tf.constant([[5,3],[8,3]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 13],
       [18, 13]], dtype=int32)>

In [24]:
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15,  9],
       [24,  9]], dtype=int32)>

In [25]:
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -2],
       [ 3, -2]], dtype=int32)>

In [26]:
tensor / 4

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.25, 0.75],
       [2.  , 0.75]])>

## Matrix multiplication


In [27]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 24],
       [64, 33]], dtype=int32)>

In [28]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 24],
       [64, 33]], dtype=int32)>

In [29]:
tf.reshape(tensor,shape = (1,2,2))

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 3],
        [8, 3]]], dtype=int32)>

In [30]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 8],
       [3, 3]], dtype=int32)>

In [31]:
A = tf.constant([1,2])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [32]:
tf.cast(A,dtype=tf.float16)


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [33]:
tf.cast(A,dtype=tf.int64)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>

In [34]:
D = tf.abs(tf.constant([-1,-7]))
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

In [35]:
E = tf.constant(np.random.randint(0,100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([92, 99, 73, 13, 84,  7, 78, 29, 64, 40, 71, 73, 33, 95, 22, 38, 58,
       77, 41, 30, 92, 71, 25, 17, 67, 77,  9, 95, 36, 14,  3, 62, 15, 73,
       79, 32, 49, 36, 70, 43, 33, 54, 82, 75, 91, 72, 53, 68, 32, 53])>

In [36]:
tf.reduce_min(E) # finds the minium element

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [37]:
tf.reduce_max(E) #finds the max element

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [38]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2695>

In [39]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [40]:
import tensorflow_probability as tfp 
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=723>

In [41]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.88959>

In [42]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [44]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [45]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [46]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [48]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [49]:
squeezed = tf.squeeze(G)
squeezed.ndim

1

In [50]:
#create the list the indices
some_list = [0,1,2,3] # could be red green blue and purple
tf.one_hot(some_list,depth=4) #depth depends upon the number of elements in array

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [51]:
tf.one_hot(some_list,depth=4,on_value="one",off_value="zero")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'one', b'zero', b'zero', b'zero'],
       [b'zero', b'one', b'zero', b'zero'],
       [b'zero', b'zero', b'one', b'zero'],
       [b'zero', b'zero', b'zero', b'one']], dtype=object)>

In [52]:
H = tf.range(0,10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [55]:
I = tf.square(H)
I


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Mon Mar 20 11:06:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [57]:
tf.config.list_physical_devices('GPU')

[]